### ISSUE TITLE
Items, and Spells

### ISSUE THREAD

**Issue by ttocsneb** [MemeMasters/Misaka-Mikoto-Meme-Machine-100-567#19]
I want to implement weapons, armor, spells, and items.

# Items

weapons and armor will be a subclass of items.  All items will have a dictionary of modifiers that are applied when active:  Armor would have an AC modifier to affect the player's ac when worn.  

## wearing items

Items also have a list of locations where they are worn to be active: A full suit of armor would be applied to [Head, Torso, Legs, Arms].  If an item can be put on multiple body parts, then the flag `optional_wear` could be set: A ring can only be placed on a finger, but it does not matter which finger.  Each body part can only have one item on it at a time unless the `stackable` flag is set: pants can be worn under armor, so pants would be stackable.  Another restriction could be that an item cannot be active unless certain body parts are free: A bow cannot be fired unless the other hand is free.

I think a full list of body parts would be as follows.

- Head
- Eyes
- Neck
- Torso
- Arms
- Hand[Right/Left]
- Wrist[Right/Left]
- Finger[0-9]
- Legs
- Feet
- Back

# Weapons

Since weapons are a subclass of items, they need to be 'active' in order to be used.  

## Rolls

Weapons have two equations.  The to hit, and the damage.  when a character calls the command `atk`, the character will try to run the equation of the to-hit.  If there is more than one active weapon, the user will have to specify the name or the body part of the weapon.  The same is applied to the command `dmg`.

# Spells

Spells are much more complicated, so I won't go into detail until I get the basics of items done.

**Comment by ttocsneb** [comment]
@TheVoiceInsideYourHead I want to know what your thoughts are on doing items like this before I do anything.

**Comment by TheVoiceInsideYourHead** [comment]
This is the kind of overhaul that needed to happen. Just leave it flexible, as I still plan to make a .json file system containing all items, spells, classes, races, monsters etc. that everything else will reference.

**Comment by ttocsneb** [comment]
What I'm thinking is that I will make everything configurable through the jsons.  even down to the stats, that way it can be compatible with other editions.

I think using Marshmallow will save us a lot of headache for the future;  I will create schemas that all items, spells, and characters must follow.

Here is a link to the marshmallow docs: https://marshmallow.readthedocs.io/en/2.x-line/quickstart.html

**Comment by ttocsneb** [comment]
This is an old and outdated issue, so I'm going to close it.
